import streamlit as st
import pandas as pd
from fpdf import FPDF
import io
import zipfile

# --- CONFIGURATION ---
# Attempt to use a standard font that supports basic English/Numbers well
FONT_FAMILY = 'Arial'

class PDFInvoice(FPDF):
    def header(self):
        # We don't put a global header here because we generate single-page PDFs mostly, 
        # but you can add a logo here if needed.
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font(FONT_FAMILY, 'I', 8)
        self.cell(0, 10, 'Generated by Invoice Splitter', 0, 0, 'C')

def clean_text(text):
    if pd.isna(text): return ""
    return str(text).strip().encode('latin-1', 'replace').decode('latin-1')

def extract_field(df, keyword, offset_range=6):
    """Searches for a keyword and returns the first non-empty value found to its right."""
    for r_idx, row in df.iterrows():
        for c_idx, cell in enumerate(row):
            if isinstance(cell, str) and keyword.lower() in cell.lower():
                # Check the next few columns for the value
                for i in range(1, offset_range):
                    if c_idx + i < len(row):
                        val = row.iloc[c_idx + i]
                        if pd.notna(val) and str(val).strip() != "":
                            return clean_text(val)
    return ""

def extract_table_data(df):
    """Finds the table headers and extracts the rows below them."""
    items = []
    start_row = -1
    
    # 1. Find the header row (contains "Description" and "Qty")
    for r_idx, row in df.iterrows():
        row_str = row.astype(str).str.lower().tolist()
        if any("description" in s for s in row_str):
            start_row = r_idx
            break
            
    if start_row == -1: return []

    # 2. Iterate rows below header until we hit "Total" or end
    # We map columns based on the header row structure
    # Assuming standard layout: Description | ... | Qty | ... | Total
    
    # Get column indices for key fields from the header row
    headers = df.loc[start_row]
    col_map = {'desc': -1, 'qty': -1, 'total': -1, 'date': -1}
    
    for c_idx, cell in enumerate(headers):
        val = str(cell).lower()
        if "description" in val: col_map['desc'] = c_idx
        elif "qty" in val: col_map['qty'] = c_idx
        elif "total" in val and "grand" not in val: col_map['total'] = c_idx
        elif "date" in val: col_map['date'] = c_idx

    # Extract rows
    for r_idx in range(start_row + 1, len(df)):
        row = df.loc[r_idx]
        
        # Stop if we hit the totals section
        if row.astype(str).str.contains("Total", case=False).any():
            break
            
        # Get data
        desc = clean_text(row.iloc[col_map['desc']]) if col_map['desc'] != -1 else ""
        qty = clean_text(row.iloc[col_map['qty']]) if col_map['qty'] != -1 else ""
        total = clean_text(row.iloc[col_map['total']]) if col_map['total'] != -1 else ""
        date = clean_text(row.iloc[col_map['date']]) if col_map['date'] != -1 else ""
        
        if desc: # Only add if there is a description
            items.append((desc, date, qty, total))
            
    return items

def generate_styled_pdf(df_slice, filename):
    pdf = PDFInvoice(orientation='P', unit='mm', format='A4')
    pdf.add_page()
    pdf.set_font(FONT_FAMILY, size=10)
    
    # --- 1. Header Info extraction ---
    hospital = "Andalusia Hospitals Smouha" # Hardcoded or extracted
    visit_no = extract_field(df_slice, "Visit")
    invoice_no = extract_field(df_slice, "Invoice")
    patient_name = extract_field(df_slice, "Patient Name")
    file_no = extract_field(df_slice, "File No")
    admission = extract_field(df_slice, "Date of Admission")
    insurer = extract_field(df_slice, "Insurer")
    physician = extract_field(df_slice, "Physician")

    # --- 2. Draw Header Section ---
    pdf.set_font(FONT_FAMILY, 'B', 16)
    pdf.cell(0, 10, hospital, 0, 1, 'C')
    pdf.set_font(FONT_FAMILY, 'B', 12)
    pdf.cell(0, 10, "DISCHARGE INVOICE", 0, 1, 'C')
    pdf.ln(5)

    # --- 3. Draw Info Grid ---
    pdf.set_font(FONT_FAMILY, size=10)
    
    # Helper to print a label: value pair
    def print_field(label, value):
        pdf.set_font(FONT_FAMILY, 'B', 10)
        pdf.cell(40, 6, label, 0, 0)
        pdf.set_font(FONT_FAMILY, '', 10)
        pdf.cell(50, 6, value, 0, 0)

    # Row 1
    print_field("Invoice No:", invoice_no)
    print_field("Visit No:", visit_no)
    pdf.ln(6)
    
    # Row 2
    print_field("Patient Name:", patient_name)
    print_field("File No:", file_no)
    pdf.ln(6)

    # Row 3
    print_field("Admission:", admission)
    print_field("Insurer:", insurer)
    pdf.ln(6)

    # Row 4
    print_field("Physician:", physician)
    pdf.ln(15)

    # --- 4. Draw Table ---
    # Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font(FONT_FAMILY, 'B', 10)
    pdf.cell(90, 8, "Description", 1, 0, 'C', 1)
    pdf.cell(30, 8, "Date", 1, 0, 'C', 1)
    pdf.cell(20, 8, "Qty", 1, 0, 'C', 1)
    pdf.cell(30, 8, "Total", 1, 1, 'C', 1)

    # Table Rows
    items = extract_table_data(df_slice)
    pdf.set_font(FONT_FAMILY, '', 9)
    
    grand_total = 0.0
    
    for desc, date, qty, total in items:
        # Simple cleanup of total for math
        try:
            val = float(total.replace(',', ''))
            grand_total += val
        except: pass

        pdf.cell(90, 8, desc[:45], 1)
        pdf.cell(30, 8, date, 1, 0, 'C')
        pdf.cell(20, 8, qty, 1, 0, 'C')
        pdf.cell(30, 8, total, 1, 1, 'R')
        
    pdf.ln(8)
    
    # --- 5. Total ---
    pdf.set_font(FONT_FAMILY, 'B', 10)
    pdf.cell(140, 8, "Grand Total:", 0, 0, 'R')
    pdf.cell(30, 8, f"{grand_total:,.3f}", 1, 1, 'R')

    return pdf

# --- MAIN WEB APP ---
st.title("🏥 Smart Invoice Splitter")
st.write("Upload your bulk CSV/Excel. This tool extracts Patient Info & Visit Number to create formatted PDFs.")

uploaded_file = st.file_uploader("Upload File", type=['csv', 'xlsx'])

if uploaded_file:
    if st.button("Process Invoices"):
        with st.spinner('Analyzing file structure...'):
            try:
                # Force string type to prevent reading numbers as floats which messes up "contains"
                if uploaded_file.name.endswith('.csv'):
                    # Using latin-1 encoding is safer for some legacy CSV exports
                    df = pd.read_csv(uploaded_file, header=None, skip_blank_lines=False, encoding='latin-1') 
                else:
                    df = pd.read_excel(uploaded_file, header=None)
            except Exception as e:
                st.error(f"Read Error: {e}")
                st.stop()

            # Identify Start Points
            # We look for "Andalusia" OR "DISCHARGE INVOICE" to find the start block
            mask = df.apply(lambda row: row.astype(str).str.contains('Andalusia Hospitals', case=False).any(), axis=1)
            start_indices = df.index[mask].tolist()
            
            # Safety: If start_indices is empty, try looking for "VAT No"
            if not start_indices:
                mask = df.apply(lambda row: row.astype(str).str.contains('VAT No', case=False).any(), axis=1)
                start_indices = df.index[mask].tolist()

            start_indices.append(len(df))

            # Prepare ZIP
            zip_buffer = io.BytesIO()
            count = 0
            
            with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
                progress = st.progress(0)
                total = len(start_indices) - 1
                
                for i in range(total):
                    # Update progress
                    progress.progress((i + 1) / total)
                    
                    # Slice
                    start = start_indices[i]
                    end = start_indices[i+1]
                    # We give it a buffer of 1 row overlap just in case
                    invoice_df = df.iloc[start:end].reset_index(drop=True)
                    
                    # Extract Visit Number for Filename
                    visit_num = extract_field(invoice_df, "Visit")
                    if not visit_num or visit_num.lower() == "nan":
                        safe_name = f"Invoice_{i+1}"
                    else:
                        safe_name = "".join([c for c in visit_num if c.isalnum() or c in ('-','_')])
                    
                    # Generate PDF
                    try:
                        pdf = generate_styled_pdf(invoice_df, safe_name)
                        pdf_bytes = pdf.output(dest='S').encode('latin-1')
                        zip_file.writestr(f"{safe_name}.pdf", pdf_bytes)
                        count += 1
                    except Exception as e:
                        # If a single invoice fails, log it but don't stop the whole process
                        st.warning(f"Skipped one invoice due to data error: {e}")

            st.success(f"Processing Complete! Created {count} PDFs.")
            
            st.download_button(
                label="📥 Download ZIP",
                data=zip_buffer.getvalue(),
                file_name="Processed_Invoices.zip",
                mime="application/zip"
            )
